image: actinius/docker-arduino-ci:latest

variables:
  DOCKER_DRIVER: overlay
  BINDIR: $CI_PROJECT_DIR/bin
  JSONURL: http://downloads.sodaq.net/test/package_test_sodaq_samd_index.json
  BOARD: SODAQ:samd:sodaq_one

stages:
  - compile_1_6_13
  - compile_1_7_0

before_script:
  #- env
  #- pwd
  #- bash ./make-version.sh
  #- cd ..
  - arduino --pref sketchbook.path=$PWD --save-prefs
  - arduino --pref compiler.warning_level=more --save-prefs
  - arduino --pref boardsmanager.additional.urls=${JSONURL} --save-prefs
  #- mkdir -p /usr/local/share/arduino/hardware/sodaq/samd
  #- git clone -b v1.6.12.1-sodaq https://github.com/SodaqMoja/SodaqCore-samd.git /usr/local/share/arduino/hardware/sodaq/samd
  #- git clone https://github.com/SodaqMoja/Sodaq_RN2483.git /usr/local/share/arduino/libraries/Sodaq_RN2483

compile_1_6_13:
  stage: compile_1_6_13
  artifacts:
    paths:
      - $BINDIR/${CI_PROJECT_NAME}-1.6.13.bin
  script:
    #- env
    #- pwd
    - rm -rf ${BINDIR}
    - mkdir ${BINDIR}
    - arduino --install-boards "SODAQ:samd:1.6.13"
    - arduino --pref build.path=${BINDIR} --verbose --verify --board ${BOARD} ${CI_PROJECT_NAME}/${CI_PROJECT_NAME}.ino
    - mv ${BINDIR}/${CI_PROJECT_NAME}.ino.bin ${BINDIR}/${CI_PROJECT_NAME}-1.6.13.bin

compile_1_7_0:
  stage: compile_1_7_0
  artifacts:
    paths:
      - $BINDIR/${CI_PROJECT_NAME}-1.7.0.bin
      - $BINDIR/${CI_PROJECT_NAME}-1.7.0.hex
  script:
    #- env
    #- pwd
    - rm -rf ${BINDIR}
    - mkdir ${BINDIR}
    - arduino --install-boards "SODAQ:samd:1.7.0"
    - arduino --pref build.path=${BINDIR} --verbose --verify --board ${BOARD} ${CI_PROJECT_NAME}/${CI_PROJECT_NAME}.ino
    - mv ${BINDIR}/${CI_PROJECT_NAME}.ino.bin ${BINDIR}/${CI_PROJECT_NAME}-1.7.0.bin
    - mv ${BINDIR}/${CI_PROJECT_NAME}.ino.hex ${BINDIR}/${CI_PROJECT_NAME}-1.7.0.hex